bot:
  system:
    cpuModelNames:
      - AMD Ryzen 5 5600G with Radeon Graphics
      - Intel Core i9-10900K
      - AMD Ryzen 9 5900X
      - Intel Core i7-11700K
      - AMD Ryzen 7 5800X
      - Intel Core i5-11600K
      - AMD Ryzen 5 5600X
      - Intel Core i3-1135G7
      - AMD Ryzen 3 5400G
      - Intel Core i3-10100
      - AMD Ryzen 5 3600
      - Intel Core i5-10400
      - AMD Ryzen 7 3800X
      - Intel Core i7-10700K
      - AMD Ryzen 9 3900X
      - Intel Core i9-11900K
      - AMD Ryzen 5 2400G
      - Intel Core i3-8100
      - AMD Ryzen 7 2700X
      - Intel Core i5-8600K
      - AMD Ryzen 3 3200G
      - Intel Core i7-9700K
      - AMD Ryzen 5 1500X
      - Intel Core i3-3225
      - AMD Ryzen 9 5950X
      - Intel Core i9-11980XE
      - AMD Ryzen 7 4800H
      - Intel Core i7-8850H
      - AMD Ryzen 5 4500U
      - Intel Core i5-1135G7

    renderers:
      - "ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001638) Direct3D11 vs_5_0 ps_5_0, D3D11)"
      - "ANGLE (NVIDIA, GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)"
      - "ANGLE (Intel, Iris Xe Graphics (0x00008086) Direct3D11 vs_5_0 ps_5_0, D3D11)"

    vendors:
      - "Google Inc. (AMD)"
      - "NVIDIA"
      - "Intel"
    osList:
      - "windows"
      - "linux"
