bot:
  twitter:
    list:
      - pojle26268757, 2jPK6*KRt#%lht, prokicpuhk@hotmail.com, 7ZM5AVB425OTKXVB
      - qljxh36986541, jwQUOrsdCCR3dd, ayanleurtis@hotmail.com, W6HAXXY3IIYLBUDP
      - xrtjr83712216, WYnY(nsi*%*$P@, ztphfugbtgs77@hotmail.com, IONUSSK7PM2CHE33
      - qlbbs19556973, bqaOlto)7CGiV0, m5bozwhvfa@hotmail.com, DHQL36AAHLQAPVVC
      - wqytr34335919, cvA2U3Bo9#fReA, fod42opqu@outlook.com, IYDJKSWSTWCDLVEQ
      - gnjag74165476, fT%1ar$^CVTKnP, hikriwodemu@outlook.com, 2LFGFQEZ7NPCV2KQ
      - xbjlm97852221, )sashbFrbz4HoA, g69cx70s59r1e@outlook.com, F3TLTMADB3P7ZAT4
      - fajet78759845, n!i*4wV@rdTfG6, hz8z2t27l@outlook.com, FUT7L2RUG7QVFB2Q
      - qavlu37119263, s#mo(QvUeq0MM6, g67jntpizqedy@hotmail.com, Z7MJOM23Q2Z7CT4J
      - ybuao53554418, Zy*HCjS)IxK#TL, fgihq235hvw@hotmail.com, SJZEPGGUDCLLE32D
      - dlxli51797942, vM(UM69EZ0P9wu, vwkyj30nmc1v@hotmail.com, N2RDXI5S32M32JGI
      - omtgg37867213, CyvV$veMSVV9ry, m71z9km22eb@outlook.com, QGFXRD6XCWKE5RAD
      - fskmn63733285, yQ&kQ*P&5M@ISp, fuz5x04ly@outlook.com, ZDZDVJVBQTPK4JOD
      - afngb76441746, jqP7kY2%E7SOkX, ni6c75p7xe8wr@hotmail.com, O7XYBLSJHIUWVUFX
      - hydnd62166442, HthRnj!X27F@rR, ibt5jxmbxk@outlook.com, YTYRY64GXFKG3BP4
      - ktvho43119796, CWbp29pE0MMD#T, zhtqkw9y4dzq5@outlook.com, UH6DH42QJ7MKZZIB
      - udcgj72173895, JNRwB6g2LT6mK4, eel0jyuzw@hotmail.com, BXMTR3PX3QV6KK2G
      - mgjeq48167782, Zs$3EsD7JlvW3y, yhfjtq226bcpe@hotmail.com, RKS63CDG3LIMHC7T
      - tqlco73151837, 6$QSlG303*0TWX, m9b6w1v9y@outlook.com, UPTZUFVOM3FITT3T
      - iusuv36764879, FZJPfbg%%%rj%i, kv4plywnv@hotmail.com, BIBKPSDL2QBTSUQH
      - mbxgp92149819, zgLV(8IfVvPzB7, yadisibezat@hotmail.com, FP6WZESZGN5OUWMB
      - iigcg53483988, 6cF7NzobxKm4M9, szr6t5frv8f@outlook.com, YTUJA22FMS3NJWTC
      - utebd77355968, *wikqTYC&mDy9o, fjvsm455tt2yj@hotmail.com, OCEXSII6GA4GH5EC
      - kxexr66259358, UwdN!!O#^7BOHW, ueudup8o8orn@hotmail.com, DKBFNP3A5YTXLBW4
      - isqwk56171547, %po9NzDbaf@@YT, z1bce0eklq@hotmail.com, 3X6DPGQMUDVIOHLR
      - gstmp25785553, HUs&9w4sYQuqSC, lagxmvgpm@outlook.com, MHEL7XBE54SRAI3M
      - zzqug36947649, ^ollTNp)wvgx^j, yhuvzz9p2up8@outlook.com, UVSJVVCXPC5BOHGF
      - hctjk19523749, dgudj#i9P9xp$Q, rrohbz1k2@outlook.com, GWNYUWSXZD5QAZF5
      - fskxg12774145, ZUmPSZxhGA0qeC, noha1c2ynu@outlook.com, SVTNVPDKUUCQFZZK
      - jbmqk78153326, dgIs9UjQ2NS6Mr, x8ovbjiet@outlook.com, 7XYLGWORDD7IJNKN
      - ttwow72422549, !9RC(mZN^hPp5z, gc8xyjn8r8z@outlook.com, PGXHTTYZDURH5YDM
      - ulsep89439382, jUj(8&f61&99@w, kominoledvi@hotmail.com, CUWRSJ2U5F6KEIJG
      - mhcnq14578183, 6%qEbHB$dlRpLv, zq7oeocrj9zw@hotmail.com, EDAOOD3G3S4TJCYL
      - mbzir87318116, MZL@V0YSptz*px, pblw3rdiy@outlook.com, 4O7ZZGK7U2ZT56CZ
      - wmoqu76559927, *)QKjAtBeofBF%, viishfoffa97@hotmail.com, TO35WKFSF3CVBVML
      - timar15667217, IYO30@E9qKL$Aa, em7fb4fevhu9@hotmail.com, 5JFGBAGP54HTY3PC
      - ntlki94553365, f&rYRS%bE$kvjA, mlfbritz2k5@outlook.com, 2RCAZ644Q5CIKWJQ
      - yvckp75959852, hss8nm*Eq51LdV, j2osfio87@hotmail.com, RJ3EUEJ65PTOINX3
      - whbdq32569926, *s%@%(2R&CLKL1, fr4lhk7lo26k@outlook.com, DXRNG6BON4VKDW5T
      - frlcv83747555, oqKKgP!BsaKKow, msoakusazt@hotmail.com, UPZJPFJLR2DFDZ7B
      - gvicy72824877, Ji0$iogdyFmG@j, vnc3y4tsugg@hotmail.com, KIMBYTQQ3RH4WNNS
      - dzadq13878124, Gym9@BFkSPTVIG, hessnboder36@outlook.com, LAJE3VKNIUC2AU5H
      - anvyh14954762, UxdY&3TM)o^Zvp, fvb5tojse06ie@hotmail.com, 3KCRX422IT732CV5
      - "quoze59943919, #WTQ!D2!6MoTgC, n8s16tizwdr0j@hotmail.com, 7DBTAACK2FZHIUPN"
      - kqohr32898213, uKAjRk2OTr#4b&, jeyr8l3pddgka@outlook.com, 6XVFH7NP2ISJ3DBL
      - lwwug75212768, rw)QF8VtfhVY%b, qjwrw3o48h4i4@hotmail.com, G5EED2PKDAEZJ4BX
      - qpzxg87881866, OW)kh66xyZp%Op, wfmdtothwyfzs@hotmail.com, WY7HQWMH5FTRC52Y
      - ttywx87786296, BTf9*AtqTjOzgx, zwwqld10d2lv@outlook.com, VNS2WIMT77EFKCNR
      - zemqu59383237, My5Q4UsCaZMz5A, y8f0daytnuj2n@hotmail.com, QRLYB2BINAQM2GCW
      - ytbin77993989, &hW2lIR(3UlG4K, chhxij3e33a4w@hotmail.com, DMLPUQX4GG3Q4LWK
