bot:
  app:
    gpunet:
      name: gpu_net
      solAddress:
        - GygWGDfDv6gGpUSnqaKCD7FfUAZWoBin9Cou3n2sUVDd
        - 2kr93oGUV8rhrTyGLGiwwq4488rciUQKnKtvMMnN8fYC
        - HmbVdtsWaYM8ihEEHyavsT1Fc9QVnDaN2wLExKedRvaV
        - AdLZBzr4A28sbBShK551Q6sdevhrVLBcBeN49doPJqU4
        - Fy2z8tm3Z1HrKkZ2p4ijVcU4nT131JYY694tM2Wkwbji
        - 4ipQ9w5jPaM5viTHCsCoxd27e3n73J3p1EMtRJ76Jtu2
        - iCqdneSMHDxWCg2F1dajG1waVKGrmGACZPoCSq68Dko
        - ED8n6dCgtShTmFGFiTU7k7ub2iCrdmVkG2YQMvxz7orA
        - CD5yFiFPTFJ7nA2imjGdAE5vEh6yM8e7wS1XnGatPGUv
        - 94N4V3TZxpdkBbsU3QiTempG67XzQkMWw4AA662BU8EA
        - BG2miqJxyLK3o44L7FiEe9iZHL9i9t8g7ZGuHChASJX6
        - DJFNF8ait3WPg7DVwYyK5zeeJ43orkRZGAMXAdYTv2ag
        - 5wpd688Yf5brEhVShkCuU9ArL2WpGGoQZjwqpMiSNNzv
        - GZR3CZLQYx72KRWfCsWww7MfmqvUf5n1jXoaBqtZRNK9
        - 7zMuTqxs5s21tvcD61pt4SJDzPs1ht7pGpgaRwgyK7xE
        - 61BXK9rmebwCsm3wUtpni49Kpd6cR2Cqh6hrkuVRu33D
        - 8BySbz8TEiPSsoz9fQr13gNnhN81kYU6gLauEGLjcru3
        - 93FnL1jcZ2woV7mduFrKwitvmqZQCXgwf7yqiYgssY6G
        - SWFcrp7UWhApnjZe6DQoKSq7LFZpXLUSjpZCABUhwZ2
        - AeffT3VnbL2JcUBkjr18YKzjm7UfYuXdJYdP8YTh3yAG
        - De3Ub9bzaWEojYdmkAgysidRhndpPpwWKxStn6c95dH
        - 9QYu3ALfZsubyS8tbSMUv6pm59Nh3x76CJvmpb2QoVyb
        - C7UurAUMTSAuiMSxLF2rZsi6tThAaw2iUh9xrAJaGc9T
        - HazvgkC9Gf4e5NUiofuGLxT8wDt5jhomRoaTXjs6QzQR
        - 9v7XiELgJJBiJhaHAhaFpDQEnmrkpXw1JFF5mmWkbUiH
        - DPgDmMdTgZaRSVgdBm1JFfYe9HQcCT5bGmjCNGt2EjR
        - 9xJBH2zLMDQ4EPwzGyVPC9ngFbS9ZTctUMDejaHaBExG
        - ZyoPcPAnRTEWSNKXHe8uSaHpS8M81WXhwK2w9JpRGEt
        - 5gTuYA6HEzRhKPP5NWc44D7FQ14zcPZr4ugQbveX5x85
        - Gk2cShazw2EgLGeGfN2UNBMQk6ynyqavLdCwgE3FzBB9
        - EzBfxZCxpVrkRyGt5uDxxetGbvdDvFy5bvdtNkXUhHeY
        - GNP7SHJ5363Ww8eX74Mv1xLgtvXrqpwqvVq2rKabsLvf
        - FFDaqpmURLF4s5s8cY8eAiXytpFXv8r2Y7eCSvuEaDgP
        - BMvkkQSwMd1jyNMz61TT2P9v3PM1ZJ9idjxBoAm1taZF
        - C6b2McbRWeNZciHaaMiYWcYK2qGkfhWYbRjswFiJqRpE
        - 7L7ehP5FPULj3HWQdWSqmDB4U5tfnzxzvCbYPAtK74PZ
        - 9AECDtv2Pe3R7ohjChXdFNDBgKpqeeZW8CTGLQn5AhwS
        - J4SjAEhygZaXPaX8Zbzxb2A3BGe3wTkz9Bpc65FGU5E6
        - EAjhLcsXsu2KFbPQP7VvQjrNkm9JmgkhuumLzAFVNtyx
        - C15ahwCnzMPej9LM1xXYda67VB4J7VdDr3ntHbMdgsbH
        - 5R98fc7rJJnhNVig8A93cXGUy5mrEUsBsJXbe71Hezht
        - DmyYVjW3zt1rpUqFu6Zgavc9dYJxKsd5VHvbwAxDK3qe
        - 4yPcmjMzri1Yzmjerp4zSJvsnuvaMzwndCnm4Au9rGCw
        - C2zsQ1ABYNPRroW6qc5oBXQtkwn1saA6wVsNNtokqmsU
        - 3spGHAdFRCabjLRfvpXNLJ75h34CdP2sBzzkkaHxApoU
        - CAb2zZSwTzHwQQJUYZFvn47H2jS56XCHZBo9tESq1A1V
        - 31HzBegZQass4FpJ2ys9oNAM2sRECPrYay8E3BpnJz6F
        - FebPZpkDmbPyNyG1i1vghdjRbG9FSUxAr9a2fRDJyJzh
        - FKAYuXt4uai7BUuY4EFpb2No82Xw2cvG6EDzSwoWTtji
        - 7M29zC4GMvuPG8szUv7xqHCJ63BFxwHNfcxvUEAMmfVG
