# 应用程序名称
spring:
  application:
    name: my-spring-boot-app
  datasource:
    url: "jdbc:sqlite://Users/helei/develop/ideaworkspace/depinbot/DepinBot/core/botData/db/auto_bot.db"
    driver-class-name: org.sqlite.JDBC

    # HikariCP配置
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 60000
      max-lifetime: 1800000
      pool-name: HikariPool
      connection-test-query: SELECT 1
      minimum-idle: 10


mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isValid  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
  mapper-locations: classpath:/mapper/*.xml


# 其他配置
logging:
  level:
    org.springframework: ERROR
#    cn.com.helei.bot.core: DEBUG
